#pragma once

#include <cstdint>

namespace MDLEnums
{
	enum class Flags : int32_t
	{
		AUTOGENERATED_HITBOX           = 0x00000001,
		USES_ENV_CUBEMAP               = 0x00000002,
		FORCE_OPAQUE                   = 0x00000004,
		TRANSLUCENT_TWOPASS            = 0x00000008,
		STATIC_PROP                    = 0x00000010,
		USES_FB_TEXTURE                = 0x00000020,
		HASSHADOWLOD                   = 0x00000040,
		USES_BUMPMAPPING               = 0x00000080,
		USE_SHADOWLOD_MATERIALS        = 0x00000100,
		OBSOLETE                       = 0x00000200,
		UNUSED                         = 0x00000400,
		NO_FORCED_FADE                 = 0x00000800,
		FORCE_PHONEME_CROSSFADE        = 0x00001000,
		CONSTANT_DIRECTIONAL_LIGHT_DOT = 0x00002000,
		FLEXES_CONVERTED               = 0x00004000,
		BUILT_IN_PREVIEW_MODE          = 0x00008000,
		AMBIENT_BOOST                  = 0x00010000,
		DO_NOT_CAST_SHADOWS            = 0x00020000,
		CAST_TEXTURE_SHADOWS           = 0x00040000,
		VERT_ANIM_FIXED_POINT_SCALE    = 0x00200000
	};
}
